export enum Payment {
  PAYMENT_STARTED = 'PAYMENT_STARTED',
  PAYMENT_CALLER = 'PAYMENT_CALLER',
  PAYMENT_DEFAULT = 'PAYMENT_DEFAULT',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
}

export enum InputCard {
  SET_CREDIT_CARD_INPUT_CALLER = 'SET_CREDIT_CARD_CALLER',
  SET_CREDIT_CARD_INPUT = 'SET_CREDIT_CARD_INPUT',
}
