export enum FetchOrders {
  FETCH_ORDERS_STARTED = 'FETCH_ORDERS_STARTED',
  FETCH_ORDERS_CALLER = 'FETCH_ORDERS_CALLER',
  FETCH_ORDERS_DEFAULT = 'FETCH_ORDERS_DEFAULT',
  FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED',
  FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS',
}
