export enum GetBookByCategorie {
  GET_BOOK_BY_CATEGORY_STARTED = 'GET_BOOK_BY_CATEGORY_STARTED',
  GET_BOOK_BY_CATEGORY_CALLER = 'GET_BOOK_BY_CATEGORY_CALLER',
  GET_BOOK_BY_CATEGORY_DEFAULT = 'GET_BOOK_BY_CATEGORY_DEFAULT',
  GET_BOOK_BY_CATEGORY_FAILED = 'GET_BOOK_BY_CATEGORY_FAILED',
  GET_BOOK_BY_CATEGORY_SUCCESS = 'GET_BOOK_BY_CATEGORY_SUCCESS',
}
