export enum SignUpInputs {
  SET_SIGNUP_INPUT_CALLER = 'SET_SIGNUP_INPUT_CALLER',
  SET_SIGNUP_INPUT = 'SET_SIGNUP_INPUT',
}

export enum SignUpNewAccount {
  SIGNUP_ACCOUNT_CALLER = 'SIGNUP_ACCOUNT_CALLER',
  SIGNUP_ACCOUNT_STARTED = 'SIGNUP_ACCOUNT_STARTED',
  SIGNUP_ACCOUNT_FAILED = 'SIGNUP_ACCOUNT_FAILED',
  SIGNUP_ACCOUNT_SUCCESS = 'SIGNUP_ACCOUNT_SUCCESS',
  SIGNUP_ACCOUNT_DEFAULT = 'SIGNUP_ACCOUNT_DEFAULT',
}
