export enum SignUpSuccess {
  SIGNUP_ACCOUNT_SUCCESS = 'SIGNUP_ACCOUNT_SUCCESS',
}

export enum LoginSuccess {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
}

export enum UpdateAccount {
  UPDATE_ACCOUNT_CALLER = 'UPDATE_ACCOUNT_CALLER',
  UPDATE_ACCOUNT_STARTED = 'UPDATE_ACCOUNT_STARTED',
  UPDATE_ACCOUNT_FAILED = 'UPDATE_ACCOUNT_FAILED',
  UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS',
  UPDATE_ACCOUNT_DEFAULT = 'UPDATE_ACCOUNT_DEFAULT',
}

export enum Logout {
  DO_LOGOUT_CALLER = 'DO_LOGOUT_CALLER',
  DO_LOGOUT = 'DO_LOGOUT',
}
