enum NavigationScreens {
  LIBRARY_DASHBOARD_SCREEN = 'stack.library.screen',
  LIBRARY_BOOK_DETAIL_SCREEN = 'LIBRARY_BOOK_DETAIL_SCREEN',
  LIBRARY_BOOK_CART_SCREEN = 'LIBRARY_BOOK_CART_SCREEN',
  LIBRARY_BOOK_SEARCH_SCREEN = 'LIBRARY_BOOK_SEARCH_SCREEN',
  LIBRARY_BOOKS_ABOUT_SCREEN = 'LIBRARY_BOOKS_ABOUT_SCREEN',
  LIBRARY_BOOKS_ORDERSCREEN = 'LIBRARY_BOOKS_ORDERSCREEN',
  LIBRARY_BOOKS_SIGNUP_SCREEN = 'LIBRARY_BOOKS_SIGNUP_SCREEN',
  LIBRARY_BOOKS_PAYMENT_SCREEN = 'LIBRARY_BOOKS_PAYMENT_SCREEN',
  LIBRARY_BOOKS_PROFILE_SCREEN = 'LIBRARY_BOOKS_PROFILE_SCREEN',
  LIBRARY_BOOKS_LOGIN_SCREEN = 'LIBRARY_BOOKS_LOGIN_SCREEN',
  LIBRARY_BOOKS_CATEGORIES_SCREEN = 'LIBRARY_BOOKS_CATEGORIES_SCREEN',
  //SIDE MENU SCREEN IDS
  LIBARARY_SIDEMENU = 'stack.library.sidemenu',
  LIBARARY_CENTER_ID = 'stack.library.center',
}

export default NavigationScreens;
