export enum SearchBook {
  SEARCH_BOOK_STARTED = 'SEARCH_BOOK_STARTED',
  SEARCH_BOOK_CALLER = 'SEARCH_BOOK_CALLER',
  SEARCH_BOOK_DEFAULT = 'SEARCH_BOOK_DEFAULT',
  SEARCH_BOOK_FAILED = 'SEARCH_BOOK_FAILED',
  SEARCH_BOOK_SUCCESS = 'SEARCH_BOOK_SUCCESS',
}
