export enum FetchBooks {
  FETCH_BOOK_STARTED = 'FETCH_BOOK_STARTED',
  FETCH_BOOK_CALLER = 'FETCH_BOOK_CALLER',
  FETCH_BOOK_DEFAULT = 'FETCH_BOOK_DEFAULT',
  FETCH_BOOK_FAILED = 'FETCH_BOOK_FAILED',
  FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS',
}

export enum ViewSelectedBook {
  SET_SELECTED_VIEW_CALLER = 'SET_SELECTED_VIEW_CALLER',
  SET_SELECTED_VIEW = 'SET_SELECTED_VIEW',
}
